// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIEzamDkjhrtD41WW-R_kuRd4yZMWERXA',
    appId: '1:82806746003:web:78903178c79a0321e45666',
    messagingSenderId: '82806746003',
    projectId: 'ifa-11312136',
    authDomain: 'ifa-11312136.firebaseapp.com',
    storageBucket: 'ifa-11312136.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRDYsmGtUHTD7dekjElFWuxhYYjsbkQtA',
    appId: '1:82806746003:android:72f4d8ddf78ca823e45666',
    messagingSenderId: '82806746003',
    projectId: 'ifa-11312136',
    storageBucket: 'ifa-11312136.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL5trkjuXYTXT2z6wxL3B-vyHIBwENax8',
    appId: '1:82806746003:ios:1c874afde1db96d4e45666',
    messagingSenderId: '82806746003',
    projectId: 'ifa-11312136',
    storageBucket: 'ifa-11312136.appspot.com',
    iosBundleId: 'com.example.ifa11312136',
  );
}
